version: "3.9"
services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: booking
      MYSQL_USER: booking
      MYSQL_PASSWORD: booking
    ports: ["3307:3306"]
    volumes: [ "mysql-data:/var/lib/mysql" ]
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_0900_ai_ci"

  redis:
    image: redis:7
    restart: unless-stopped
    ports: ["6379:6379"]

  adminer:
    image: adminer
    restart: unless-stopped
    ports: ["8080:8080"]

volumes:
  mysql-data:
